version: "3.9"
services:
  test:
    image: "eleicoes2022"
    volumes:
      - .:/app
    command: python3 -m pytest
  download:
    image: "eleicoes2022"
    volumes:
      - .:/app
    command: python3 src/downloader.py
  run:
    image: "eleicoes2022"
    volumes:
      - .:/app
    command: python3 src/main.py